const dummyUsers = [
   {
      ACTIVE: true,
      uid: "fagah",
      programDate: "",
      username: "test1",
      adminUnread: false,
      email: "test1@email.com",
   },
   {
      ACTIVE: true,
      uid: "ggpgpg",
      programDate: "",
      username: "test2",
      adminUnread: false,
      email: "test2@email.com",
   },
   {
      ACTIVE: true,
      uid: "gglglg",
      programDate: "",
      username: "test3",
      adminUnread: false,
      email: "test3@email.com",
   },
   {
      ACTIVE: false,
      uid: "gpwirn",
      programDate: "",
      username: "test4",
      adminUnread: false,
      email: "test4@email.com",
   },
   {
      ACTIVE: false,
      uid: "vivp",
      programDate: "",
      username: "test5",
      adminUnread: false,
      email: "test5@email.com",
   },
   {
      ACTIVE: false,
      uid: "pov",
      programDate: "",
      username: "test6",
      adminUnread: false,
      email: "test6@email.com",
   },
   {
      ACTIVE: false,
      uid: "ag;a;g",
      programDate: "",
      username: "test7",
      adminUnread: true,
      email: "test7@email.com",
   },
   {
      ACTIVE: true,
      uid: "daffffff",
      programDate: "",
      username: "test8",
      adminUnread: false,
      email: "test8@email.com",
   },
   {
      ACTIVE: true,
      uid: "dffashh",
      programDate: "",
      username: "test9",
      adminUnread: false,
      email: "test9@email.com",
   },
   {
      ACTIVE: false,
      uid: "ag;llllll;g",
      programDate: "",
      username: "test10",
      adminUnread: false,
      email: "test10@email.com",
   },
   {
      ACTIVE: true,
      uid: "vivllllp",
      programDate: "",
      username: "test11",
      adminUnread: false,
      email: "test11@email.com",
   },
   {
      ACTIVE: false,
      uid: "aeyhmm",
      programDate: "",
      username: "test12",
      adminUnread: false,
      email: "test12@email.com",
   },
   {
      ACTIVE: true,
      uid: "ag;ggggggggg;g",
      programDate: "",
      username: "test13",
      adminUnread: false,
      email: "test13@email.com",
   },
   {
      ACTIVE: false,
      uid: "vivppppppppp",
      programDate: "",
      username: "test14",
      adminUnread: false,
      email: "test14@email.com",
   },
   {
      ACTIVE: true,
      uid: "povlllklnlknlkn",
      programDate: "",
      username: "test15",
      adminUnread: false,
      email: "test15@email.com",
   },
   {
      ACTIVE: true,
      uid: "ag;a;g16",
      programDate: "",
      username: "test16",
      adminUnread: false,
      email: "test16@email.com",
   },

];

export default dummyUsers;